In [1]:
from Absenteeism_model import *
model = absenteeism_model("model", "scaler")
model.load_and_clean_data("Absenteeism_new_data.csv")
model.predicted_outputs()

,Reason_1,Reason_2,Reason_3,Reason_4,Month,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Probability,Prediction
0,0,0.0,0,1,6,179,30,19,1,0,0,0.164989,0
1,1,0.0,0,0,6,361,28,27,0,1,4,0.848853,1
2,0,0.0,0,1,6,155,34,25,0,2,0,0.322333,0
3,0,0.0,0,1,6,179,40,22,1,2,0,0.272553,0
4,1,0.0,0,0,6,155,34,25,0,2,0,0.753419,1
5,1,0.0,0,0,6,225,28,24,0,1,2,0.717803,1
6,1,0.0,0,0,6,118,46,25,0,2,0,0.582759,1
7,0,0.0,0,1,6,179,30,19,1,0,0,0.164989,0
8,0,0.0,0,1,6,118,37,28,0,0,0,0.141990,0
9,1,0.0,0,0,6,118,37,28,0,0,0,0.515281,1
10,0,0.0,0,1,6,378,36,21,0,2,4,0.423057,0
11,0,0.0,1,0,6,118,50,31,0,1,0,0.660926,1
12,0,0.0,1,0,6,233,31,21,1,1,8,0.428076,0
13,0,0.0,0,1,6,179,30,19,1,0,0,0.164989,0
14,0,0.0,0,0,6,235,48,33,0,1,5,0.065018,0
15,0,0.0,0,0,6,268,33,25,1,0,0,0.182504,0
16,0,0.0,1,0,6,118,50,31,0,1,0,0.660926,1
17,1,0.0,0,0,6,179,30,19,1,0,0,0.559329,1
18,0,0.0,0,1,6,291,40,25,0,1,1,0.360810,0
19,1,0.0,0,0,7,179,30,19,1,0,0,0.564139,1
20,0,0.0,0,1,7,118,37,28,0,0,0,0.144387,0
21,0,0.0,0,1,7,233,31,21,1,1,8,0.066619,0
22,1,0.0,0,0,7,118,37,28,0,0,0,0.520159,1
23,1,0.0,0,0,7,118,37,28,0,0,0,0.520159,1
24,0,0.0,0,1,7,233,31,21,1,1,8,0.066619,0
25,0,0.0,0,1,7,235,43,38,0,1,0,0.502571,1
26,0,0.0,1,0,7,233,31,21,1,1,8,0.432865,0
27,1,0.0,0,0,7,228,58,22,0,2,1,0.572281,1
28,0,0.0,0,1,7,118,37,28,0,0,0,0.144387,0
29,1,0.0,0,0,7,228,58,22,0,2,1,0.572281,1
30,0,0.0,0,1,7,189,33,25,0,2,2,0.287413,0
31,0,0.0,0,1,7,118,37,28,0,0,0,0.144387,0
32,0,0.0,0,1,7,361,28,27,0,1,4,0.471324,0
33,0,0.0,0,1,7,225,28,24,0,1,2,0.287640,0
34,1,0.0,0,0,7,369,31,25,0,3,0,0.967270,1
35,1,0.0,0,0,7,289,33,30,0,2,1,0.911909,1
36,1,0.0,0,0,7,235,37,29,1,1,1,0.781152,1
37,0,0.0,0,0,7,118,40,34,0,1,8,0.019255,0
38,0,0.0,0,0,7,231,39,35,0,2,2,0.266796,0
39,0,0.0,0,0,7,179,53,25,0,1,1,0.054833,0

In [2]:
import pymysql

In [3]:
connex = pymysql.connect(database = "predicted_outputs", user="root", password="Totustuus23")

In [4]:
cursor = connex.cursor()

### Checkpoint

In [5]:
df_new_obs = model.predicted_outputs()

### .execute( )

In [6]:
cursor.execute("SELECT * FROM predicted_outputs")

0

Python variables can be used as arguments of the __.execute( )__ method as well

We will create a structure that will insert the ro's information from __df_new_obs__ into a row in our database in MySQL ("predicted_outputs").

## Creating the INSERT Statement

In [7]:
insert_query = "INSERT INTO predicted_outputs VALUES"
insert_query

'INSERT INTO predicted_outputs VALUES'

In [8]:
df_new_obs.shape

(40, 13)

In [9]:
df_new_obs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Probability', 'Prediction'], dtype=object)

In [10]:
for i in range(df_new_obs.shape[0]):
    insert_query +='('
    
    for j in range(df_new_obs.shape[1]):
        insert_query += str(df_new_obs[df_new_obs.columns.values[j]][i]) + ', '
    
    insert_query = insert_query[:-2] + '), '
insert_query = insert_query[:-2] + ';'

In [11]:
insert_query

'INSERT INTO predicted_outputs VALUES(0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.16498928381864866, 0), (1, 0.0, 0, 0, 6, 361, 28, 27, 0, 1, 4, 0.8488532865920595, 1), (0, 0.0, 0, 1, 6, 155, 34, 25, 0, 2, 0, 0.32233259347405957, 0), (0, 0.0, 0, 1, 6, 179, 40, 22, 1, 2, 0, 0.27255251265613467, 0), (1, 0.0, 0, 0, 6, 155, 34, 25, 0, 2, 0, 0.753418714373868, 1), (1, 0.0, 0, 0, 6, 225, 28, 24, 0, 1, 2, 0.717802840113377, 1), (1, 0.0, 0, 0, 6, 118, 46, 25, 0, 2, 0, 0.58275864929247, 1), (0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.16498928381864866, 0), (0, 0.0, 0, 1, 6, 118, 37, 28, 0, 0, 0, 0.14198977166566812, 0), (1, 0.0, 0, 0, 6, 118, 37, 28, 0, 0, 0, 0.5152805265548128, 1), (0, 0.0, 0, 1, 6, 378, 36, 21, 0, 2, 4, 0.42305657645310263, 0), (0, 0.0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.6609255375231461, 1), (0, 0.0, 1, 0, 6, 233, 31, 21, 1, 1, 8, 0.42807556415265563, 0), (0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.16498928381864866, 0), (0, 0.0, 0, 0, 6, 235, 48, 33, 0, 1, 5, 0.06501760206804405, 0), (0, 0.0, 0, 0, 6, 268, 33, 25, 1, 0, 0, 0.1825037511829397, 0), (0, 0.0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.6609255375231461, 1), (1, 0.0, 0, 0, 6, 179, 30, 19, 1, 0, 0, 0.5593287098555096, 1), (0, 0.0, 0, 1, 6, 291, 40, 25, 0, 1, 1, 0.3608098260622448, 0), (1, 0.0, 0, 0, 7, 179, 30, 19, 1, 0, 0, 0.5641385654962516, 1), (0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.14438667812060302, 0), (0, 0.0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.06661898385598246, 0), (1, 0.0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.520158706710399, 1), (1, 0.0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.520158706710399, 1), (0, 0.0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.06661898385598246, 0), (0, 0.0, 0, 1, 7, 235, 43, 38, 0, 1, 0, 0.5025713200872176, 1), (0, 0.0, 1, 0, 7, 233, 31, 21, 1, 1, 8, 0.4328654266608341, 0), (1, 0.0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.5722812511585748, 1), (0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.14438667812060302, 0), (1, 0.0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.5722812511585748, 1), (0, 0.0, 0, 1, 7, 189, 33, 25, 0, 2, 2, 0.28741254892644885, 0), (0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.14438667812060302, 0), (0, 0.0, 0, 1, 7, 361, 28, 27, 0, 1, 4, 0.47132416733458965, 0), (0, 0.0, 0, 1, 7, 225, 28, 24, 0, 1, 2, 0.2876395770621671, 0), (1, 0.0, 0, 0, 7, 369, 31, 25, 0, 3, 0, 0.9672700291033173, 1), (1, 0.0, 0, 0, 7, 289, 33, 30, 0, 2, 1, 0.9119088584636542, 1), (1, 0.0, 0, 0, 7, 235, 37, 29, 1, 1, 1, 0.7811524917551141, 1), (0, 0.0, 0, 0, 7, 118, 40, 34, 0, 1, 8, 0.019254835998042286, 0), (0, 0.0, 0, 0, 7, 231, 39, 35, 0, 2, 2, 0.2667958877558453, 0), (0, 0.0, 0, 0, 7, 179, 53, 25, 0, 1, 1, 0.0548331953195142, 0);'

In [12]:
cursor.execute(insert_query)

40

In [13]:
connex.commit()

In [15]:
connex.close()